# TODO add MP3, MP4
tags_conversion = {
    "flac": {
        "album": {"ALBUM"},
        "albumsort": {"ALBUMSORT"},
        "title": {"TITLE"},
        "titlesort": {"TITLESORT"},
        "work": {"WORK"},
        "artist": {"ARTIST"},
        "artistsort": {"ARTISTSORT"},
        "albumartist": {"ALBUMARTIST"},
        "albumartistsort": {"ALBUMARTISTSORT"},
        "date": {"DATE"},
        "originaldate": {"ORIGINALDATE"},
        "originalyear": {"ORIGINALYEAR"},
        "composer": {"COMPOSER"},
        "composersort": {"COMPOSERSORT"},
        "lyricist": {"LYRICIST"},
        "writer": {"WRITER"},
        "conductor": {"CONDUCTOR"},
        "performer-instrument": {"PERFORMER"},
        "remixer": {"REMIXER"},
        "arranger": {"ARRANGER"},
        "engineer": {"ENGINEER"},
        "producer": {"PRODUCER"},
        "djmixer": {"DJMIXER"},
        "mixer": {"MIXER"},
        "label": {"LABEL"},
        "grouping": {"GROUPING"},
        "subtitle": {"SUBTITLE"},
        "discsubtitle": {"DISCSUBTITLE"},
        "tracknumber": {"TRACKNUMBER"},
        "totaltracks": {"TRACKTOTAL", "TOTALTRACKS"},
        "discnumber": {"DISCNUMBER"},
        "totaldiscs": {"DISCTOTAL", "TOTALDISCS"},
        "compilation": {"COMPILATION"},
        "comment-description": {"COMMENT"},
        "genre": {"GENRE"},
        "_rating": {"RATING:user@email"},
        "bpm": {"BPM"},
        "mood": {"MOOD"},
        "lyrics-description": {"LYRICS"},
        "media": {"MEDIA"},
        "catalognumber": {"CATALOGNUMBER"},
        # "show": set(),
        # "showsort": set(),
        # "podcast": set(),
        # "podcasturl": set(),
        "releasestatus": {"RELEASESTATUS"},
        "releasetype": {"RELEASETYPE"},
        "releasecountry": {"RELEASECOUNTRY"},
        "script": {"SCRIPT"},
        "language": {"LANGUAGE"},
        "copyright": {"COPYRIGHT"},
        "license": {"LICENSE"},
        "encodedby": {"ENCODEDBY"},
        "encodersettings": {"ENCODERSETTINGS"},
        "gapless": set(),
        "barcode": {"BARCODE"},
        "isrc": {"ISRC"},
        "asin": {"ASIN"},
        "musicbrainz_recordingid": {"MUSICBRAINZ_TRACKID"},
        "musicbrainz_trackid": {"MUSICBRAINZ_RELEASETRACKID"},
        "musicbrainz_albumid": {"MUSICBRAINZ_ALBUMID"},
        "musicbrainz_artistid": {"MUSICBRAINZ_ARTISTID"},
        "musicbrainz_albumartistid": {"MUSICBRAINZ_ALBUMARTISTID"},
        "musicbrainz_releasegroupid": {"MUSICBRAINZ_RELEASEGROUPID"},
        "musicbrainz_workid": {"MUSICBRAINZ_WORKID"},
        "musicbrainz_trmid": {"MUSICBRAINZ_TRMID"},
        "musicbrainz_discid": {"MUSICBRAINZ_DISCID"},
        "acoustid_id": {"ACOUSTID_ID"},
        "acoustid_fingerprint": {"ACOUSTID_FINGERPRINT"},
        "musicip_puid": {"MUSICIP_PUID"},
        "musicip_fingerprint": {"FINGERPRINT"},
        "website": {"WEBSITE"},
    },
}
